version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: gamerstore_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gamestore
    ports:
      - '5432:5432'
    volumes:
      - postgres_gamestore:/var/lib/postgresql/data

volumes:
  postgres_gamestore:
